"""
Write db/seed_real.sql: real Keepa price histories for a few products from
studies/Prices.csv, so the model can run locally without a Keepa key.

Prices are real. Dates are shifted so each history ends on the day you seed,
because the model reads "today" relative to the latest price.

Usage:
    cd backend && .venv/bin/python scripts/make_real_seed.py
"""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from ml.evaluate import load_prices

PRODUCTS = [
    ("B0BS1T9J4Y", "Garmin Forerunner 265 Running Smartwatch, 46mm", "Garmin", "Wearables"),
    ("B0CCZ26B5V", "Bose QuietComfort Headphones", "Bose", "Headphones"),
    ("B0CRGJC5ZD", "Samsung 32\" Odyssey G55C QHD Curved Gaming Monitor", "Samsung", "Monitors"),
    ("B0DDV3FRHR", "Sony WH-1000XM5 Noise Cancelling Headphones", "Sony", "Headphones"),
    ("B0D8WJYSF9", "Google Streamer 4K", "Google", "Streaming"),
    ("B0C8PR4W22", "Beats Studio Pro Wireless Headphones", "Beats", "Headphones"),
]
OUT = os.path.join(os.path.dirname(__file__), "..", "db", "seed_real.sql")


def _sql(v):
    return "NULL" if v != v or v is None else f"{float(v):.2f}"


def _int(v):
    return "NULL" if v != v or v is None else str(int(v))


def main() -> None:
    px = load_prices()
    lines = [
        "-- ==============================================================",
        "-- BuyWise real-history seed (generated by scripts/make_real_seed.py)",
        "-- Real Keepa prices for a few products. Dates are shifted so each",
        "-- history ends today. Predictions are computed by the model the",
        "-- first time /predict is called for each product.",
        "-- ==============================================================",
        "USE buywise;",
        "",
    ]
    for asin, title, brand, category in PRODUCTS:
        h = px[(px.asin == asin) & px.price.notna()].sort_values("date")
        last = h.date.max()
        title_sql = title.replace("'", "''").replace('"', '\\"')
        lines += [
            f"-- {title}: {len(h)} price events",
            f"INSERT INTO products (asin, title, brand, category) VALUES ('{asin}', '{title_sql}', '{brand}', '{category}')",
            "ON DUPLICATE KEY UPDATE title = VALUES(title);",
            f"SET @pid = (SELECT product_id FROM products WHERE asin = '{asin}');",
            f"DELETE FROM prices WHERE product_id = @pid;",
            f"DELETE FROM predictions WHERE product_id = @pid;",
            "INSERT INTO prices (product_id, price, timestamp, availability, deal_flag, used_price, count_new, count_used) VALUES",
        ]
        vals = [
            f"(@pid, {r.price:.2f}, CURDATE() - INTERVAL {(last - r.date).days} DAY, TRUE, FALSE, "
            f"{_sql(r.used_price)}, {_int(r.count_new)}, {_int(r.count_used)})"
            for r in h.itertuples()
        ]
        lines += [",\n".join(vals) + ";", ""]
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {os.path.normpath(OUT)}")


if __name__ == "__main__":
    main()
